services:
  - type: web
    name: telegram-bot
    env: python
    plan: free # or another plan depending on your needs
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true